// Generated from the public Universal Category System v8.2.1 translation workbook.
// The original spreadsheet is not bundled.

export const ucsCategories = [
  { code: '气体 / AIR', glyph: "◇" },
  { code: '航空器 / AIRCRAFT', glyph: "◇" },
  { code: '警报 / ALARMS', glyph: "◇" },
  { code: '环境 / AMBIENCE', glyph: "◇" },
  { code: '动物 / ANIMALS', glyph: "◇" },
  { code: '归档 / ARCHIVED', glyph: "◇" },
  { code: '提示音 / BEEPS', glyph: "◇" },
  { code: '钟铃 / BELLS', glyph: "◇" },
  { code: '鸟类 / BIRDS', glyph: "◇" },
  { code: '船舶 / BOATS', glyph: "◇" },
  { code: '子弹 / BULLETS', glyph: "◇" },
  { code: '卡通 / CARTOON', glyph: "◇" },
  { code: '陶瓷 / CERAMICS', glyph: "◇" },
  { code: '链条 / CHAINS', glyph: "◇" },
  { code: '化学 / CHEMICALS', glyph: "◇" },
  { code: '钟表 / CLOCKS', glyph: "◇" },
  { code: '布料 / CLOTH', glyph: "◇" },
  { code: '通讯 / COMMUNICATIONS', glyph: "◇" },
  { code: '电脑 / COMPUTERS', glyph: "◇" },
  { code: '生物 / CREATURES', glyph: "◇" },
  { code: '人群 / CROWDS', glyph: "◇" },
  { code: '声音设计 / DESIGNED', glyph: "◇" },
  { code: '拆除 / DESTRUCTION', glyph: "◇" },
  { code: '沙土 / DIRT & SAND', glyph: "◇" },
  { code: '门 / DOORS', glyph: "◇" },
  { code: '抽屉 / DRAWERS', glyph: "◇" },
  { code: '电流 / ELECTRICITY', glyph: "◇" },
  { code: '器具 / EQUIPMENT', glyph: "◇" },
  { code: '爆炸 / EXPLOSIONS', glyph: "◇" },
  { code: '放屁 / FARTS', glyph: "◇" },
  { code: '打斗 / FIGHT', glyph: "◇" },
  { code: '火 / FIRE', glyph: "◇" },
  { code: '烟花 / FIREWORKS', glyph: "◇" },
  { code: '拟音 / FOLEY', glyph: "◇" },
  { code: '食物 / FOOD & DRINK', glyph: "◇" },
  { code: '脚步 / FOOTSTEPS', glyph: "◇" },
  { code: '游戏 / GAMES', glyph: "◇" },
  { code: '地热 / GEOTHERMAL', glyph: "◇" },
  { code: '玻璃 / GLASS', glyph: "◇" },
  { code: '血 / GORE', glyph: "◇" },
  { code: '枪炮 / GUNS', glyph: "◇" },
  { code: '号角 / HORNS', glyph: "◇" },
  { code: '人 / HUMAN', glyph: "◇" },
  { code: '冰 / ICE', glyph: "◇" },
  { code: '激光 / LASERS', glyph: "◇" },
  { code: '皮革 / LEATHER', glyph: "◇" },
  { code: '液体与流体 / LIQUID & MUD', glyph: "◇" },
  { code: '机器 / MACHINES', glyph: "◇" },
  { code: '魔法 / MAGIC', glyph: "◇" },
  { code: '机械 / MECHANICAL', glyph: "◇" },
  { code: '金属 / METAL', glyph: "◇" },
  { code: '马达 / MOTORS', glyph: "◇" },
  { code: '移动 / MOVEMENT', glyph: "◇" },
  { code: '乐句 / MUSICAL', glyph: "◇" },
  { code: '自然灾害 / NATURAL DISASTER', glyph: "◇" },
  { code: '物件 / OBJECTS', glyph: "◇" },
  { code: '纸张 / PAPER', glyph: "◇" },
  { code: '塑料 / PLASTIC', glyph: "◇" },
  { code: '雨 / RAIN', glyph: "◇" },
  { code: '机器人 / ROBOTS', glyph: "◇" },
  { code: '岩石 / ROCKS', glyph: "◇" },
  { code: '绳索 / ROPE', glyph: "◇" },
  { code: '橡胶 / RUBBER', glyph: "◇" },
  { code: '科幻 / SCIFI', glyph: "◇" },
  { code: '雪 / SNOW', glyph: "◇" },
  { code: '运动 / SPORTS', glyph: "◇" },
  { code: '嗖嗖声 / SWOOSHES', glyph: "◇" },
  { code: '工具 / TOOLS', glyph: "◇" },
  { code: '玩具 / TOYS', glyph: "◇" },
  { code: '火车 / TRAINS', glyph: "◇" },
  { code: '用户界面 / USER INTERFACE', glyph: "◇" },
  { code: '植物 / VEGETATION', glyph: "◇" },
  { code: '车辆 / VEHICLES', glyph: "◇" },
  { code: '语音 / VOICES', glyph: "◇" },
  { code: '水 / WATER', glyph: "◇" },
  { code: '武器 / WEAPONS', glyph: "◇" },
  { code: '天气 / WEATHER', glyph: "◇" },
  { code: '哨音 / WHISTLES', glyph: "◇" },
  { code: '风 / WIND', glyph: "◇" },
  { code: '窗户 / WINDOWS', glyph: "◇" },
  { code: '翅膀 / WINGS', glyph: "◇" },
  { code: '木头 / WOOD', glyph: "◇" },
] as const;
